version: '3.5'

services:
  eureka-server:
    container_name: eureka-server
    build:
      context: .
      dockerfile: Dockerfile
    image: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - spring-microservice

networks:
  spring-microservice:
    external: true
