spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: account-service
                  uri: http://localhost:8081
                  predicates:
                    - Path=/api/v1/accounts/**
server:
    port: 8762
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/